# 1
# Check. Your. Data. Always.
?rock
str(rock)
head(rock)

# a)
hist(rock$shape, density = 10)
# Main bulk looks normal, but few outliers, maybe.
# Make a boxplot as well, and remember how outliers
# are defined in a boxplot (Q_n + 1.5*IQR)
boxplot(rock$shape)

# Bonus:
# If you save boxplot as an object, you can
# access more information:
b <- boxplot(rock$shape)
b
?boxplot

# b)
qqnorm(rock$shape)
qqline(rock$shape, lty = 3)
# A linear 'trend' would suggest normality.
# Here, perhaps the tails are "out of normal"


# Bonus: manually for the sake of transparency:
theoretical_quantiles <- qnorm(ppoints(length(rock$shape)))
?ppoints

ordered_sample_quantiles <- sort(rock$shape)

plot(theoretical_quantiles, ordered_sample_quantiles)
qqline(ordered_sample_quantiles, lty = 3)

# c)
# For Bowman-Shenton (Jarque-Bera) test, use your favorite implementation
# or make your own function!
library(DescTools)
JarqueBeraTest(rock$shape, robust = F)
# Essentially this tests how much sample deviates from
# normal distribution in terms of kurtosis and skewness.

# Or if you would like to Make your own:
bs.test <- function(x) {
  
  n <- length(x)
  krt <- Kurt(x, method = 1) # k As defined in the slides
  
  skw <- Skew(x)
  #BS <- n * ((skw^2 / 6) + (krt^2 / 24))
  BS <- ( n*skw^2 / 6 ) + ( n*krt^2 / 24)
  return(BS)
  
}
bs.test(rock$shape)
1 - pchisq(bs.test(rock$shape), df = 2)
# Note that, the slight difference in the test statistic value
# is due to JarqueBeraTest defining kurtosis and skewness
# differently (see source code).
# The robust argument TRUE defines skewness and kurtosis based
# on median aboslute deviation.

# Shapiro-Wilk test:
shapiro.test(rock$shape)
# The test statistic is a good approximation
# of the correlation coeffient of the qqplot()
qqnorm(rock$shape)
cor(theoretical_quantiles, ordered_sample_quantiles)

# d)
# The evidence suggests that the sample does not come from normal distribution.

# e)
?rock
# Twelve core samples from petroleum reservoirs were sampled by 4 cross-sections.
# Each core sample was measured for permeability, and each cross-section
# has total area of pores, total perimeter of pores, and shape.

# Essentially, each rock is sampled four times, therefore
# these four samples are definitely not independent.

# 2
?randu
str(randu)
head(randu)

# a)
a <- randu$x
hist(a, density = 20)

# b)
range(a)
# Random number from uniform dist. 0 to 1
# So, let's say 10 categories is 'suitable'
# ( Change the value of b to try with different
# number of categories. )
b <- 10
ad <- cut(a, breaks = seq(0,1,1/b), include.lowest = T)
ad
# Frequency table:
table(ad)
# Barplot:
# Observed probability:
barplot(table(ad) / sum(table(ad)),
        ylim = c(0,0.3), yaxt = 'n');axis(2, las = 2)

# Expected probability:
abline(h = 1/b, lty = 3, col="red")

# c)
# Expected probability dist. is uniform:
E_p <- rep(1/b,b)

# d)
# The null hypothesis is that the data was generated by the uniform distribution on [0, 1]
# and the alternative that it was not.
?chisq.test
chisq.test(table(ad) , p = E_p)

# Or manually, for transparency:
# Test statistic
chi_2 <- sum((table(ad) - rep(length(a)/b,b))^2 / rep(length(a)/b,b))
chi_2
# And the p-value, df = n - 1
1 - pchisq(chi_2, df = b-1)

# e)
# The test p-value is 0.5493
# -> no evidence against H0, it is still plausible that the data is from Uniform[0, 1].
# By choosing the categories suitably, it is most likely possible to get the opposite result
# (recall the Type I and II errors). However, this should not be taken advantage of in practice...

# BONUS: pvalue fishing
# Cut the data into {2,3,...400} intervals and
# calculate p-value for each subset:
pvals <- NA
for(i in 1:399) {
  b <- i+1
  ad <- cut(a, breaks = b, include.lowest = T)
  E_p <- rep(1/b,b)
  chi_2 <- sum((table(ad) - rep(length(a)/b,b))^2 / rep(length(a)/b,b))
  pvals[i] <- 1 - pchisq(chi_2, df = b-1)
  #pvals[i] <- chisq.test(table(ad), p = rep(1/b,b))$p.value # with chisq.test function
  
}
sort(pvals)

# 3
?Titanic
str(Titanic)
Titanic

# a)
A <- apply(Titanic, c(2,4), sum)
A

# or

?margin.table
x <- margin.table(Titanic, c(2, 4))
x
# b)
# Stacked barplot can handle the task adequately:
barplot(A/sum(A), ylim = c(0,1), yaxt = 'n', col = c('grey30','grey'));axis(2, las = 2)
legend('topright', legend = c('Male','Female'), pch = 15, col = c('grey30','grey'))
# Or a mosaic plot:
mosaicplot(A)

# c)

# c.
# It seems plausible that there were no quotas on Female/Male passengers
# on the ship. As such, both factors had their margins non-fixed and 
# the correct test is the test for independence.
chisq.test(A)

# Very low p-value
# -> sex and survival status are not independent 
# -> females had stat. significant higher chance of surviving.